apiVersion: v1
kind: Pod
metadata:
  name: devtools
spec:
  containers:
    - name: devtools
      image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
      command: 
        - /bin/bash
        - -c
      args: 
        - "while true; do sleep 30s; done;"
      securityContext:
        privileged: true
      resources:
        {{- toYaml .Values.resources | nindent 10 }}