apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysecrets.properties
  namespace: agimei01-dev
spec:
  encryptedData:
    mysecrets.properties: AgBsdYU8neRxL2+2bzEq37XUV+xASE1UhVK9TkPcwM9adu8fo2FbWBVawm3LC85Y/Me26eonCjC2r57QfmHj5J2dwOgZakjLDvqEPXHa47tEatyLxDu3EESh3llW4zjXFFtct5ikobVSkG2xLnjKQ7Al06Kg7ocB2cVUA8BlIka7lefd37PsPTDC8uBx/wlku4+9Y5WIvZCW4PNMH6AXqIfe+O39jjrCcYDH+zIvMKVWurf2onUW86gM27ik1VENiBBzll+rMONa8wqhKxejRozjJIJj6rTd3Ub8HgfGlmgRNTa+rUjZdzReE3dARmDryxZi8LERNfCUL2wv+9QZnHKudL1OdFbVyDfMe6wMVxRi2tjHhXmLSO3g162Cy8X3TqhnVctgnpRdhkv21CbnTTcawG48FgbncdpQRAbnXrJV+7wFAYgad9Su8K8d64IdDoAdGm02s+4LaLvZNheS1LnUCQH51kl8bdPZnBAXJe3MnUEqa9KsC5bLxXy1Gv0QjbeEGqqQi/47zg16n6KFEKknmngiqVZUAOfpj4fQb+0nzdtXo/ozhN3fMOGPN5hcjije1j84RmnfAqL4JiWuv8iKjeiS3uDzvS2cRrkH+AVGmiNlzvgLe4BQJSmw/jA6ev+tZEXq9bA8AttKOoGLrKaXyuNzwA0d5qHLyc8uJ9DZjrfk7vp0fM73qScuAcIqcY/AoTq63rYj9IOs8gh3bJQWxu+S1LY/aI8NC9g3txP5W+8=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: mysecrets.properties
      namespace: agimei01-dev

