apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: datasource-exampledb
  namespace: agimei01-dev
spec:
  encryptedData:
    datasource-exampledb.xml: AgAfyw0lSzzyrfG/HYqAy7+0Qx1bWFQUkUKugMkjZDSYY0mcJyQ2qGas1A9c62wcgLSg7D6it4fql07IotfPyvOMN2syowV0Rq3mN+sBSkQ+x1TDb/f0Lxn/riN0nCFM8Ot6GNLAR/mIOcWjdLmiag0iVgYPVgMaRc1PtPBFdTgAIXDl6UQ5NxCdD2gyN0j7wF4oCqq4HoHtpxHAouTnU+Jz8t4a5J9loEKw1djIal4h6dIlCnGsUgUMxzAdGimoHqmdu9vO6PLVFq6rnp0imMXd2a/gNlWsC7MRFb2fFAMorinSjK4J+mo6cJDKQ7lmOdWxNwDxMnoVbYZghogDpUZjK4to5ArxJ3YCFj7gbmmDUi/MDDIZumei18AQRD4kyA4A2vqu+/bdFHAcsVSkDJRRDrixkFDq7/dEVlILUuJvmMKTLmXNKuNYrLx3d1reQt3tlwez/YUxyMaWP57kiAo0enGYYjAuAVlHPeiGuQgB8gg2ChrB9UG33GyuT3o+0InscIngBHgig69bSvXsfCEoXWRDvSBLqpe6U+8KVb6KMTcy0yNCWfRFfL2J/W9IJ2mJmSNjvvRRnwoaL1jbbDR+caXmxuFtQkVqmj/zdLJlHeoQ53sxKtfx7NTgE8Btoc6jBenKq+2XnVL7/Oqbe8mjGb93q55djWv4THxtrQ/yqLUQ0Kn2muZHOUIgdnEu8kLe2wiXkokD8rKtgJGd6h+3GhaUg+plDo0upMoU/gLwqeurSiGLs88Xr1j+U/le5B8cIywntLDCjQXH90Jii30JK5SzEwLrsDqlu5K3yDRaKA2ysWnXGpgmXi/RshuOZv6soOYCYDNWvAqd1k+QC7oF6vZd0pWiAfYwsx9lSUFoxiCrXT2Rq0uBvToP7bbCU9Dc0AC2yyK6z16DkGQ8I5YzwA2J+gLL1XC13s3qyjGJaHEQyW5b718FGGZ9ZSky9BMLRUryXBUDvfMVpned2PKRdBoRO7+mS5PQfIJHj7oqUZfMUJBRT03/R5047LA9G3gKyv8vOSpwADsv6hJKwYe4AqIgpQ+pRW5XSm+TRCrjzgReyCWEjbf1+wNcsBrvfahxMdpgtq3jq9rKtBiCNIcKDXFY8ADHmTilfB49TihzniPIJ5z1yzunM2Gs5RyNTe3eNA3SZVXc15knfxXTL3yLph1tPMNqFvGnxMH9uA==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: datasource-exampledb
      namespace: agimei01-dev

