apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysecrets
  namespace: agimei01-dev
spec:
  encryptedData:
    mysecrets.properties: AgBio2Fui8JEhYLNAE9yTNJhMhZt5ZbM67UmtQpNdPrBaRanGRS6Z6bDt/SlY7mGwKZUu7PgP7cqEyh8RxpIQFnGY2WW6sBpCWfDN0VnrFLXE0O3U5ER+lKjv9Qpqu5BUOLIAuoy3bruVVBdAmxGWWtCQjtihJKclu7Y7hL2uZvGylUaZZDlfT9Fv+fC4YK4/SqtT2RvSEPIzV+01Icm1Gl2lHRQ6zLqu3b5FBzP7iPQqQm4FFL2szxj/El3Nc4SwWaQbp2Wcwda+DSqj3UzOgiWOaHdRWSIYL9T8GzGM1K0Zd8ot9Ir48G90f4D0sLlhKHalyDxRX0rH9iM5uVBKOqWJBfuKsb/3rLDkX4aQxOvz2cXac9auKDKW6VYoXuLGKoBtmm/Owexb8NQ75XZVctDrDFRmxldkEEC8d8am8PtIXtufI64IhR2lZlZTRk3dr60gNqcr/lpklLz0H6v9bJEnunK1MPhs8UDOXbHH/NrbLvvKlgGMUR5NoQwlaPwU6JmU8ieXueaJv/nABTpYYYxuFux/s3OdNw7Jaxd68Vzt6sfnTkR5RGQ1oqwDPG7nJHiM2jq6TSP3h9eQyKWIBK7bBil3U+o6qXxu5AjPa65kCjWnct5CdTRgHD9ctfXFCWVyOzxLTqd8j5q0HAGuU0QrDNTagFeK5/i6L8WhYkW8QKdZhJ2+ggb3zc6sHlO8RtCEkxla3DKajht05mn27Ba6U1dW04u7b/kIU0T3FYkfkI=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: mysecrets
      namespace: agimei01-dev

